export { type User, type UserRole, type LoginPayload, type SignupPayload, type AuthResponse, type SessionUser } from "./auth";
export { type Feature, type Step, type Stat } from "./homepage";
export {
  type LectureType,
  LECTURE_TYPE_LABELS,
  type LectureStatus,
  type AttendanceStatus,
  type AttendanceMethod,
  type Module,
  type ModuleWithStats,
  type CreateModulePayload,
  type UpdateModulePayload,
  type Lecture,
  type LectureWithModule,
  type LectureWithStats,
  type CreateLecturePayload,
  type UpdateLecturePayload,
  type AttendanceRecord,
  type AttendanceWithStudent,
  type MarkAttendancePayload,
  type Student,
  type StudentWithAttendance,
  type ModuleStudent,
  type EnrollStudentsPayload,
  type UnenrollStudentsPayload,
  type DashboardStats,
  type RecentLecture,
  type ModuleAttendanceSummary,
  type SSEAttendanceEvent,
  type ApiResponse,
  type AdminStats,
  type AdminLecturer,
  type CreateLecturerPayload,
  type AdminRecentActivity,
} from "./dashboard";
